"use client";

import MDFormatting from "@/components/chat/MDFormatting";

const DOCS_TEXT = [
  "[TOC]",
  "",
  "# qPal documentation",
  "",
  "qPal lets you organize conversations into **workspaces**, each with its own chat history and member list.",
  "",
  "## Layout",
  "",
  "- **Left sidebar** – profile & explore navigation, list of workspaces, theme toggle.",
  "- **Center** – the active workspace chat.",
  "- **Right** – members for the active workspace (on large screens).",
  "",
  "## Workspaces",
  "",
  "- **Create**:",
  "  - Click the **+** next to *Workspaces* in the left sidebar, or",
  "  - Click **Create Workspace** in the empty state.",
  "- **Rename / Star / Delete**:",
  "  - Hover a workspace, click the **⋯** button, then choose an action.",
  "- **Reorder**:",
  "  - Drag the handle on the left of a workspace to move it up or down.",
  "- **Switch**:",
  "  - Click a workspace name in the sidebar to open its chat.",
  "",
  "## Members",
  "",
  "- The right panel shows members of the current workspace.",
  "- Click the **+** button in the members header to add someone by `@username`.",
  "",
  "## Sending messages",
  "",
  "- Type your message in the input at the bottom of the chat.",
  "- Click **Send** (paper-plane icon) to send.",
  "- On desktop:",
  "  - **Enter** sends the message.",
  "  - **Shift+Enter** inserts a new line.",
  "",
  "## Using Markdown in chat",
  "",
  "You can format messages using Markdown. Below are the main features supported by qPal.",
  "",
  "### Headings",
  "",
  "```md",
  "# Title",
  "## Section",
  "### Subsection",
  "```",
  "",
  "### Emphasis",
  "",
  "- **Bold**: `**bold**`",
  "- *Italic*: `*italic*`",
  "- ***Bold + italic***: `***both***`",
  "- ~~Strikethrough~~: `~~text~~`",
  "- ==Highlight==: `==important==`",
  "",
  "### Inline code & code blocks",
  "",
  "- Inline code: `` `const x = 1` ``",
  "",
  "Fenced code blocks:",
  "",
  "```ts",
  "function greet(name: string) {",
  "  console.log('Hello ' + name);",
  "}",
  "```",
  "",
  "You can also indent code by 4 spaces to create an indented code block.",
  "",
  "### Lists & task lists",
  "",
  "```md",
  "- Item 1",
  "- Item 2",
  "  - Nested item",
  "",
  "1. First",
  "2. Second",
  "```",
  "",
  "Task lists:",
  "",
  "```md",
  "- [x] Done task",
  "- [ ] Pending task",
  "```",
  "",
  "### Links & images",
  "",
  "```md",
  "[OpenAI](https://openai.com)",
  "<https://example.com>",
  "",
  "![Alt text](https://placekitten.com/200/200 \"Optional title\")",
  "```",
  "",
  "### Tables",
  "",
  "```md",
  "| Column | Column |",
  "|:------ | -----:|",
  "| Left   | Right |",
  "```",
  "",
  "### Mentions, issues, commits",
  "",
  "- `@username` → mention badge",
  "- `#123` → issue/PR link style",
  "- `a1b2c3d` (7–40 hex) → commit code style",
  "",
  "### Emoji shortcodes",
  "",
  "- `:smile:`  → 😄",
  "- `:rocket:` → 🚀",
  "- `:tada:`   → 🎉",
  "- `:thumbsup:` / `:thumbsdown:`",
  "",
  "### Colored text",
  "",
  "```md",
  "[color=red]Important[/color]",
  "[color=#ff00aa]Custom hex color[/color]",
  "```",
  "",
  "- Named colors: `red`, `blue`, `green`, `yellow`, `pink`, `purple`, `orange`.",
  "- Or hex (`#ff00aa` or `ff00aa`).",
  "",
  "### Table of contents",
  "",
  "Add `[TOC]` on its own line to generate a table of contents (like at the top of this page).",
].join("\n");

export default function Docs() {
  return (
    <div className="h-full overflow-y-auto p-4">
      <div className="mx-auto max-w-2xl">
        <h1 className="mb-1 text-lg font-semibold">Docs</h1>
        <p className="mb-4 text-sm text-muted-foreground">
          How to use workspaces, chat, and Markdown in qPal.
        </p>

        {/* No card wrapper here */}
        <MDFormatting text={DOCS_TEXT} className="mt-2" />
      </div>
    </div>
  );
}
